// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bthmirlinsnvfhqlrnzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0aG1pcmxpbnNudmZocWxybnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODgxOTUsImV4cCI6MjA2MzE2NDE5NX0.y0EDfO3IsofSrtUCrQFUN9cmZ_k3zwwAqqZvpoERxW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);